version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    env_file:
      - variables.env

    ports:
      - "3306:3306"